#!/usr/bin/env sh

A2O_DEV_SAMPLE_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export A2O_DEV_SAMPLE_ROOT
export A2O_DEV_SAMPLE_COMPOSE_PROJECT="${A2O_DEV_SAMPLE_COMPOSE_PROJECT:-a2o-dev-sample}"
export A2O_DEV_SAMPLE_KANBALONE_PORT="${A2O_DEV_SAMPLE_KANBALONE_PORT:-3471}"
export A2O_DEV_SAMPLE_AGENT_PORT="${A2O_DEV_SAMPLE_AGENT_PORT:-7394}"
export A2O_DEV_SAMPLE_AGENT_URL="${A2O_DEV_SAMPLE_AGENT_URL:-http://127.0.0.1:${A2O_DEV_SAMPLE_AGENT_PORT}}"
export A2O_DEV_SAMPLE_KANBAN_URL="${A2O_DEV_SAMPLE_KANBAN_URL:-http://127.0.0.1:${A2O_DEV_SAMPLE_KANBALONE_PORT}}"
export A2O_DEV_SAMPLE_PROJECT="${A2O_DEV_SAMPLE_PROJECT:-A2ODevSampleJava}"
export A2O_DEV_SAMPLE_PACKAGE="${A2O_DEV_SAMPLE_PACKAGE:-${A2O_DEV_SAMPLE_ROOT}/reference-products/java-spring-multi-module/project-package/project.yaml}"
export A2O_DEV_SAMPLE_STORAGE_DIR="${A2O_DEV_SAMPLE_STORAGE_DIR:-${A2O_DEV_SAMPLE_ROOT}/.work/a2o-dev-sample/runtime}"
export A2O_DEV_SAMPLE_AGENT_WORKSPACE_DIR="${A2O_DEV_SAMPLE_AGENT_WORKSPACE_DIR:-${A2O_DEV_SAMPLE_ROOT}/.work/a2o-dev-sample/agent-workspaces}"
