# frozen_string_literal: true

module A3
  module Application
  end
end

require "a3/application/execution_result"
require "a3/application/handle_parent_review_disposition"
require "a3/application/start_phase"
require "a3/application/plan_next_phase"
require "a3/application/plan_next_runnable_task"
require "a3/application/schedule_next_run"
require "a3/application/execute_next_runnable_task"
require "a3/application/scheduler_loop_policy"
require "a3/application/execute_until_idle"
require "a3/application/plan_rerun"
require "a3/application/build_workspace_plan"
require "a3/application/prepare_workspace"
require "a3/application/build_scope_snapshot"
require "a3/application/build_artifact_owner"
require "a3/application/build_worker_task_packet"
require "a3/application/resolve_run_recovery"
require "a3/application/build_merge_plan"
require "a3/application/phase_execution_orchestrator"
require "a3/application/phase_execution_flow"
require "a3/application/phase_execution_strategy"
require "a3/application/run_worker_phase"
require "a3/application/run_verification"
require "a3/application/run_merge"
require "a3/application/cleanup_terminal_task_workspaces"
require "a3/application/scheduler_cleanup_runner"
require "a3/application/quarantine_terminal_task_workspaces"
require "a3/application/null_quarantine_terminal_task_workspaces"
require "a3/application/plan_persisted_rerun"
require "a3/application/recover_persisted_rerun"
require "a3/application/diagnose_blocked_run"
require "a3/application/show_task"
require "a3/application/show_run"
require "a3/application/show_watch_summary"
require "a3/application/show_scheduler_history"
require "a3/application/scheduler_state_controls"
require "a3/application/execution_process_probe"
require "a3/application/show_state"
require "a3/application/repair_runs"
require "a3/application/register_started_run"
require "a3/application/register_completed_run"
require "a3/application/start_run"
require "a3/application/show_runtime_package"
require "a3/application/doctor_runtime_environment"
require "a3/application/migrate_scheduler_store"
require "a3/application/run_runtime_canary"
require "a3/application/sync_external_tasks"
