# frozen_string_literal: true

module A3
  module Domain
  end
end

require "a3/domain/repository_error"
require "a3/domain/configuration_error"
require "a3/domain/merge_config"
require "a3/domain/merge_config_resolver"
require "a3/domain/project_context"
require "a3/domain/phase_runtime_config"
require "a3/domain/merge_source"
require "a3/domain/integration_target"
require "a3/domain/merge_plan"
require "a3/domain/merge_planning_policy"
require "a3/domain/task_repository"
require "a3/domain/run_repository"
require "a3/domain/scheduler_state_repository"
require "a3/domain/scheduler_cycle_repository"
require "a3/domain/phase_policy"
require "a3/domain/review_disposition"
require "a3/domain/rerun_policy"
require "a3/domain/blocked_diagnosis"
require "a3/domain/blocked_diagnosis_factory"
require "a3/domain/project_surface"
require "a3/domain/task"
require "a3/domain/source_descriptor"
require "a3/domain/phase_source_policy"
require "a3/domain/scope_snapshot"
require "a3/domain/review_target"
require "a3/domain/artifact_owner"
require "a3/domain/agent_artifact_upload"
require "a3/domain/agent_workspace_descriptor"
require "a3/domain/agent_job_request"
require "a3/domain/agent_job_result"
require "a3/domain/agent_job_record"
require "a3/domain/worker_task_packet"
require "a3/domain/scheduler_state"
require "a3/domain/scheduler_cycle_step"
require "a3/domain/scheduler_cycle"
require "a3/domain/slot_requirement"
require "a3/domain/workspace_policy"
require "a3/domain/workspace_plan"
require "a3/domain/prepared_workspace"
require "a3/domain/runnable_task_assessment"
require "a3/domain/phase_runtime_snapshot"
require "a3/domain/phase_execution_record"
require "a3/domain/phase_record"
require "a3/domain/evidence_record"
require "a3/domain/run"
require "a3/domain/operator_inspection_read_model"
require "a3/domain/runtime_package_descriptor"
